import type { AnalysisResult } from "@/lib/engine";

const bandLabels: Record<string, string> = {
  clear: "Clear Scope",
  review: "Needs Review",
  risky: "High Risk",
};

export function resultToMarkdown(
  result: AnalysisResult,
  projectType: string,
): string {
  const lines: string[] = [];

  lines.push("# ScopeSeal Report");
  lines.push("");
  lines.push(`**Score:** ${result.score}/100 (${bandLabels[result.band] ?? result.band})`);
  lines.push(`**Project type:** ${projectType}`);
  lines.push(`**Word count:** ${result.wordCount}`);
  if (result.sensitiveWarning) {
    lines.push("");
    lines.push("> ⚠️ **Warning:** This scope may contain sensitive or confidential content.");
  }
  lines.push("");
  lines.push("---");
  lines.push("");

  lines.push("## Category Breakdown");
  lines.push("");
  for (const cat of result.categories) {
    const note = cat.note ? ` — ${cat.note}` : "";
    lines.push(`- **${cat.label}:** ${cat.score}/100 (weight: ${cat.weight})${note}`);
  }
  lines.push("");

  if (result.missing.length > 0) {
    lines.push("## Missing Items");
    lines.push("");
    for (const item of result.missing) {
      lines.push(`- [${item.severity.toUpperCase()}] **${item.label}** — ${item.guidance}`);
    }
    lines.push("");
  }

  if (result.risks.length > 0) {
    lines.push("## Risky Wording");
    lines.push("");
    for (const risk of result.risks) {
      lines.push(`- "${risk.phrase}" (x${risk.count}) — ${risk.guidance}`);
    }
    lines.push("");
  }

  if (result.suggestions.length > 0) {
    lines.push("## Suggestions");
    lines.push("");
    result.suggestions.forEach((s, i) => {
      lines.push(`${i + 1}. ${s}`);
    });
    lines.push("");
  }

  lines.push("---");
  lines.push("");

  lines.push("## Internal Risk Summary");
  lines.push("");
  lines.push(result.outputs.internalRiskSummary);
  lines.push("");

  lines.push("## Client-Friendly Note");
  lines.push("");
  lines.push(result.outputs.clientFriendlyNote);
  lines.push("");

  lines.push("## Proposal Addition");
  lines.push("");
  lines.push(result.outputs.proposalAdditionalInfo);
  lines.push("");

  lines.push("## Rewritten Scope");
  lines.push("");
  lines.push(result.outputs.rewrittenScope);
  lines.push("");

  lines.push("---");
  lines.push("*Generated by ScopeSeal — scopeseal.codezela.com*");

  return lines.join("\n");
}
